openapi: 3.0.1
info:
  title: Web Backend
  description: Node.js code for the web backend!
  x-cortex-git:
    github:
      repository: Mooretex/starter-node
  x-cortex-tag: starter-node
  x-cortex-type: service
  x-cortex-issues:
    jira:
      labels:
        - "starter-node"
      defaultJql: 'status = "In Progress" OR status = "To Do"'
